# Generated by Django 4.2.7 on 2025-10-20 01:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('completed', 'Completed'), ('failed', 'Failed'), ('no_answer', 'No Answer'), ('busy', 'Busy')], max_length=12)),
                ('twilio_sid', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('weather_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_call_sid', models.CharField(max_length=100, unique=True)),
                ('from_number', models.CharField(max_length=17)),
                ('to_number', models.CharField(max_length=17)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WakeUpCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_time', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=17)),
                ('contact_method', models.CharField(choices=[('call', 'Phone Call'), ('sms', 'Text Message')], max_length=4)),
                ('zip_code', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='scheduled', max_length=12)),
                ('is_demo', models.BooleanField(default=False, help_text="Demo calls don't make actual calls/texts")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('next_execution', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
    ]
