# Generated by Django 4.2.7 on 2025-10-20 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wakeupcall',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wakeup_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inboundcall',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calllog',
            name='wakeup_call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='calls.wakeupcall'),
        ),
    ]
